services:
  umoja:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    mem_limit: 512m # on limite l'utilisation de la mémoire à 512 Mo
