framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enable trusted proxies for handling proxy headers
    trusted_proxies: '127.0.0.1'  # Assurez-vous que l'IP de votre proxy est incluse, généralement '127.0.0.1' si Nginx et Symfony sont sur la même machine.
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port']  # Correction ici avec les en-têtes en minuscules.

    # Enables session support
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Error logging
    php_errors:
        log: true

    # Assets
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
