name: Build Frontend

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest # on spécifie l'environnement dans lequel on exécute la pipeline

    steps:
    - name: clone du repo/accès au code source
      uses: actions/checkout@v2

    - name: installations de node dans l'environnement
      uses: actions/setup-node@v2
      with:
        node-version: '22' # on spécifie le versionnage de node quand on le tire

    - name: installations des dépendances
      run: npm install
      working-directory: ./saas_frontend

    - name: compilation du code
      run: npm run build
      working-directory: ./saas_frontend