name: Linting Backend

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest  # on spécifie l'environnement dans lequel on exécute la pipeline

    steps:
    - name: clone du repo/accès au code source
      uses: actions/checkout@v2
