name: Linting Backend

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: clone du repo/accès au code source
      uses: actions/checkout@v2

    - name: installation de php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: installations des dépendances de composer (fichier composer.json)
      run: composer install --prefer-dist --no-progress --no-interaction
      working-directory: ./saas_backend

    - name: exécution de la commande de vérification du code
      run: vendor/bin/phpcs -p --standard=PSR12 src
      working-directory: ./saas_backend
