name: Tests Backend

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: clone du repo/accès au code source
      uses: actions/checkout@v2

    - name: installation de php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: installations des dépendances de composer (fichier composer.json)
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: exécute les tests unittaires (dossier tests/)
      run: vendor/bin/phpunit --testdox